 CREATE TABLE IF NOT EXISTS SOP_EMPL
(
  EMPL_NBR VARCHAR(20) NOT NULL ,
  EMPL_NAM VARCHAR(200) NOT NULL,
  EMPL_SEC VARCHAR(100) NOT NULL,
  EMPL_DEPT VARCHAR(100) NOT NULL,
  EMPL_TIT VARCHAR(100) NOT NULL,
  COURSE_CODE VARCHAR(20) NOT NULL ,
  COURSE_NAME VARCHAR(255) NOT NULL,
	COURSE_INST_CODE VARCHAR(20) NOT NULL ,
  COURSE_INST_NAME VARCHAR(200) NOT NULL,
  C_START_DTE DATE NOT NULL,
  C_END_DTE DATE NOT NULL,
  C_RESULT VARCHAR(20) NOT NULL,
  C_TIME INT NOT NULL
	/*CONSTRAINT PRIMARY KEY(EMPL_NBR)*/
	)ENGINE=InnoDB DEFAULT CHARSET=utf8;
