CREATE TABLE IF NOT EXISTS CSS_COURSE_INST
(
  COURSE_INST_CODE VARCHAR(20) NOT NULL UNIQUE ,
  COURSE_CODE VARCHAR(20) NOT NULL,
  COURSE_INST_NAME VARCHAR(200) NOT NULL,
  C_START_DTE DATE NOT NULL ,
  C_END_DTE DATE NOT NULL,
  C_TIME INT NOT NULL,
  CONSTRAINT PRIMARY KEY (COURSE_INST_CODE)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;